<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>College Ranking Predictions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">2cool4school</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf">Presentation</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">Report</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#research-background" id="toc-research-background" class="nav-link" data-scroll-target="#research-background">Research Background</a></li>
  <li><a href="#research-question-and-hypothesis" id="toc-research-question-and-hypothesis" class="nav-link" data-scroll-target="#research-question-and-hypothesis">Research Question and Hypothesis</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#data-summary" id="toc-data-summary" class="nav-link" data-scroll-target="#data-summary">Data summary</a></li>
  </ul></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a>
  <ul class="collapse">
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data Preparation</a></li>
  <li><a href="#preliminary-exploration-and-visualization" id="toc-preliminary-exploration-and-visualization" class="nav-link" data-scroll-target="#preliminary-exploration-and-visualization">Preliminary Exploration and Visualization</a></li>
  <li><a href="#check-correlation-coefficients" id="toc-check-correlation-coefficients" class="nav-link" data-scroll-target="#check-correlation-coefficients">Check Correlation Coefficients</a></li>
  <li><a href="#build-model" id="toc-build-model" class="nav-link" data-scroll-target="#build-model">Build model</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#categorical-variable-analysis" id="toc-categorical-variable-analysis" class="nav-link" data-scroll-target="#categorical-variable-analysis">Categorical Variable Analysis</a></li>
  <li><a href="#iteration-1" id="toc-iteration-1" class="nav-link" data-scroll-target="#iteration-1">Iteration #1</a></li>
  <li><a href="#iteration-2" id="toc-iteration-2" class="nav-link" data-scroll-target="#iteration-2">Iteration #2</a></li>
  <li><a href="#iteration-3" id="toc-iteration-3" class="nav-link" data-scroll-target="#iteration-3">Iteration #3</a></li>
  <li><a href="#iteration-4" id="toc-iteration-4" class="nav-link" data-scroll-target="#iteration-4">Iteration #4</a></li>
  <li><a href="#model-results" id="toc-model-results" class="nav-link" data-scroll-target="#model-results">Model results</a></li>
  <li><a href="#r-squared-values" id="toc-r-squared-values" class="nav-link" data-scroll-target="#r-squared-values">R-Squared Values</a></li>
  <li><a href="#final-conclusion" id="toc-final-conclusion" class="nav-link" data-scroll-target="#final-conclusion">Final Conclusion</a></li>
  </ul></li>
  <li><a href="#works-cited" id="toc-works-cited" class="nav-link" data-scroll-target="#works-cited">Works Cited</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">College Ranking Predictions</h1>
<p class="subtitle lead">Report</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="cell">

</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<section id="research-background" class="level3">
<h3 class="anchored" data-anchor-id="research-background">Research Background</h3>
<p>Every year, millions of students apply to colleges across the United States, and many of them use college rankings lists from sources such as <em>US News and World Report</em>, Forbes.com, and Niche.com to to help them decide where to apply and where to go. In recent years, these lists have been heavily criticized for focusing on “exclusivity and resources, rather than accessibility and economic mobility”(1).The system can also be easily manipulated by a university if that university prioritize certain metrics to raise their rankings, as seen in Northeastern University meteoric rise from #163 to #49 on the US News and World Report list in only 17 years. The president of Northeastern University even explicitly stated that it was a top priority of the university to raise its ranking (2).</p>
<ol type="1">
<li>https://thehill.com/changing-america/enrichment/education/3641004-the-scandal-facing-college-ranking-lists-explained/</li>
</ol>
<p>(2) https://www.bostonmagazine.com/news/2014/08/26/how-northeastern-gamed-the-college-rankings/</p>
<p>These lists are important because students applying to college trust these rankings and weigh them into their college decisions. Due to the large impact that a college has on a student’s life, it is important to know where these rankings come from and what they actually measure. In this project, we will explore how influential different metrics are in determining a college’s ranking.</p>
<p>In general, we want to examine how different variables affect a school’s ranking on the <strong>Niche College Ranking List</strong> and determine which are most important to a high ranking. We plan to look at variables that are typically thought to influence school rank such as average SAT score and admission rate, but we also want to look at variables that aren’t typically thought of such as geographic region or endowment size.</p>
<p>For the sake of clarity, when we say a “low rank,” we are referring to schools with a lower numerical rank, such as #1 and #2. When we say a “high rank,” we a referring to schools with a high numerical rank, such as #497 and #498.</p>
</section>
<section id="research-question-and-hypothesis" class="level3">
<h3 class="anchored" data-anchor-id="research-question-and-hypothesis">Research Question and Hypothesis</h3>
<p><strong>Question:</strong> Which characteristics of a university are most associated with rankings on the Niche College Ranking list? Of these characteristics, what is the relationship between high and low rank?</p>
<p><strong>Hypothesis:</strong> We hypothesize that SAT/ACT scores, acceptance rate, and family income will have the strongest association with rank because since Niche’s audience is in large part students applying to college, we believe that they prioritize variables important in the college admissions process. Of these variables, we predict that SAT/ACT score will have strong negative relationship, acceptance rate will have a strong positive relationship, and family income will have a strong negative relationship with rank.</p>
<p>In our project, we will join two data sets: The Niche College Rankings list and the US Department of Education College Scorecard</p>
</section>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="data-set-1-niche" class="level4">
<h4 class="anchored" data-anchor-id="data-set-1-niche">Data Set #1: Niche</h4>
<ul>
<li><p>The first data set comes from Niche’s “2023 Best Colleges in America” list</p>
<p>(https://www.niche.com/colleges/search/best-colleges/)</p></li>
<li><p>Niche aggregates data from a variety of sources, including the US Department of Education and reviews from students and alumni, to build their list of college rankings. The rankings list is updated monthly to reflect new data that Niche receives. However, Niche only receives data from the US Department of Education on an annual basis. The Niche data was scraped by Maia on October 17-19 2022.</p></li>
<li><p>There are 500 observations, representing the top 500 schools in the United States. Each observation has two variables: <code>college</code> and <code>rank</code>.</p></li>
</ul>
</section>
<section id="data-set-2-us-department-of-education" class="level4">
<h4 class="anchored" data-anchor-id="data-set-2-us-department-of-education">Data Set #2: US Department of Education</h4>
<ul>
<li><p>The second data set comes from the US Department of Education’s College Scorecard, which is an exhaustive summary of characteristics and statistics for all colleges and universities in the United States.</p>
<p>(https://collegescorecard.ed.gov/data/)</p></li>
<li><p>The College Scorecard is updated by the Education Department as it collects new data. Data used in the scorecard comes comes from data reported by the institutions, data on federal financial aid, data from taxes, and data from other federal agencies.</p></li>
<li><p>There were 2,989 variables in the original data set, many of which we don’t need to answer our question, and since this data set was too large to load into RStudio, we used Excel to narrow this to 31 variables. We chose any variables that we thought would have an impact on college rank, and excluded redundant ones like specific breaksdowns of test scores. There are 6681 observations in the data set, representing all of the colleges and universities in the United States.</p></li>
</ul>
</section>
<section id="data-summary" class="level3">
<h3 class="anchored" data-anchor-id="data-summary">Data summary</h3>
<p>Here is a summary of the variables we will be using in our analysis.</p>
<table class="table">
<colgroup>
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 44%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>Variable Name</th>
<th><p>Categorical (C)</p>
<p>Quantitative (Q)</p></th>
<th>Description</th>
<th>Levels of Cat. Variable</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>college</td>
<td>C</td>
<td>Institution name</td>
<td></td>
</tr>
<tr class="even">
<td>rank</td>
<td>Q</td>
<td>Niche rank</td>
<td></td>
</tr>
<tr class="odd">
<td>REGION</td>
<td>C</td>
<td></td>
<td>New England, Mid East, Great Lakes, Plains, Southeast, Southwest, Rocky Mountains, Far West, Outlying Areas</td>
</tr>
<tr class="even">
<td>ACCREDAGENCY</td>
<td>C</td>
<td>Accreditor for Institution</td>
<td></td>
</tr>
<tr class="odd">
<td>CONTROL</td>
<td>C</td>
<td></td>
<td>Public, Private nonprofit, private for-profit</td>
</tr>
<tr class="even">
<td>CCBASIC</td>
<td>C</td>
<td>Carnegie Classification (basic)</td>
<td></td>
</tr>
<tr class="odd">
<td>ADM_RATE</td>
<td>Q</td>
<td>Admission rate</td>
<td></td>
</tr>
<tr class="even">
<td>UGDS</td>
<td>Q</td>
<td>Enrollment of undergraduate certificate/degree-seeking students</td>
<td></td>
</tr>
<tr class="odd">
<td>UGDS_WHITE</td>
<td>Q</td>
<td>Total share of enrollment of undergraduate degree-seeking students who are white</td>
<td></td>
</tr>
<tr class="even">
<td>UGDS_BLACK</td>
<td>Q</td>
<td>Total share of enrollment of undergraduate degree-seeking students who are black</td>
<td></td>
</tr>
<tr class="odd">
<td>UGDS_HISP</td>
<td>Q</td>
<td>Total share of enrollment of undergraduate degree-seeking students who are Hispanic</td>
<td></td>
</tr>
<tr class="even">
<td>UGDS_ASIAN</td>
<td>Q</td>
<td>Total share of enrollment of undergraduate degree-seeking students who are Asian</td>
<td></td>
</tr>
<tr class="odd">
<td>UGDS_AIAN</td>
<td>Q</td>
<td>Total share of enrollment of undergraduate degree-seeking students who are American Indian/Alaska Native</td>
<td></td>
</tr>
<tr class="even">
<td>UGDS_NHPI</td>
<td>Q</td>
<td>Total share of enrollment of undergraduate degree-seeking students who are Native Hawaiian/Pacific Islander</td>
<td></td>
</tr>
<tr class="odd">
<td>UGDS_2MOR</td>
<td>Q</td>
<td>Total share of enrollment of undergraduate degree-seeking students who are two or more races</td>
<td></td>
</tr>
<tr class="even">
<td>UGDS_NRA</td>
<td>Q</td>
<td>Total share of enrollment of undergraduate degree-seeking students who are non-resident aliens</td>
<td></td>
</tr>
<tr class="odd">
<td>UGDS_UNKN</td>
<td>Q</td>
<td>Total share of enrollment of undergraduate degree-seeking students whose race is unknown</td>
<td></td>
</tr>
<tr class="even">
<td>NPT4_PUB</td>
<td>Q</td>
<td>Average net price for Title IV institutions (public institutions)</td>
<td></td>
</tr>
<tr class="odd">
<td>NPT4_PRIV</td>
<td>Q</td>
<td>Average net price for Title IV institutions (private for-profit and nonprofit institutions)</td>
<td></td>
</tr>
<tr class="even">
<td>COSTT4_A</td>
<td>Q</td>
<td>Average cost of attendance (academic year institutions)</td>
<td></td>
</tr>
<tr class="odd">
<td>COSTT4_P</td>
<td>Q</td>
<td>Average cost of attendance (program-year institutions)</td>
<td></td>
</tr>
<tr class="even">
<td>AVGFACSAL</td>
<td>Q</td>
<td>Average faculty salary</td>
<td></td>
</tr>
<tr class="odd">
<td>PCTPELL</td>
<td>Q</td>
<td>Percentage of undergraduates who receive a Pell Grant</td>
<td></td>
</tr>
<tr class="even">
<td>C150_4</td>
<td>Q</td>
<td>Completion rate for first-time, full-time students at four-year institutions (150% of expected time to completion)</td>
<td></td>
</tr>
<tr class="odd">
<td>AGE_ENTRY</td>
<td>Q</td>
<td>Average age of entry</td>
<td></td>
</tr>
<tr class="even">
<td>FEMALE</td>
<td>Q</td>
<td>Share of female students</td>
<td></td>
</tr>
<tr class="odd">
<td>MARRIED</td>
<td>Q</td>
<td>Share of married students</td>
<td></td>
</tr>
<tr class="even">
<td>FIRST_GEN</td>
<td>Q</td>
<td>Share of first-generation students</td>
<td></td>
</tr>
<tr class="odd">
<td>FAMINC</td>
<td>Q</td>
<td>Average family income</td>
<td></td>
</tr>
<tr class="even">
<td>MD_FAMINC</td>
<td>Q</td>
<td>Median family income</td>
<td></td>
</tr>
<tr class="odd">
<td>ENDOWBEGIN</td>
<td>Q</td>
<td>Value of school’s endowment at the beginning of the fiscal year</td>
<td></td>
</tr>
<tr class="even">
<td>SAT_AVG</td>
<td>Q</td>
<td>Average SAT equivalent score of students admitted</td>
<td></td>
</tr>
<tr class="odd">
<td>ACTCMMID</td>
<td>Q</td>
<td>Midpoint of the ACT cumulative score</td>
<td></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">Methodology</h2>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">Data Preparation</h3>
<ol type="1">
<li>To get the data, we scraped from Niche.com and downloaded data from the US Department of Education, and imported. The steps were done in an R script titled <code>niche-scrape.R</code></li>
</ol>
<div class="cell">

</div>
<ol start="2" type="1">
<li>Some of the college names were slightly different between datasets, so we had to individually change names in the Department of Education dataset to match those in the Niche one before joining the two. The Observations for <code>University of South Florida - Sarasota-Manatee</code> (ranked 141) and <code>University of South Florida - St. Petersburg</code> (ranked 181) have been dropped from the <code>colleges</code> data set due to their non-existence in the <code>us_dep_of_ed</code> data set. They were not present in the data set because these two universities were combined with the main University of South Florida campus. This is why the <code>colleges</code> data set only has 498 observations.</li>
</ol>
<div class="cell">

</div>
<ol start="3" type="1">
<li>We joined the US Department of Education dataset to the Niche dataset by the college names. The first 5 rows are displayed below.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 5%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 12%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">college</th>
<th style="text-align: right;">rank</th>
<th style="text-align: right;">UNITID</th>
<th style="text-align: right;">OPEID</th>
<th style="text-align: right;">OPEID6</th>
<th style="text-align: left;">CITY</th>
<th style="text-align: left;">STABBR</th>
<th style="text-align: left;">ZIP</th>
<th style="text-align: left;">ACCREDAGENCY</th>
<th style="text-align: right;">LATITUDE</th>
<th style="text-align: right;">LONGITUDE</th>
<th style="text-align: right;">REGION</th>
<th style="text-align: right;">CCBASIC</th>
<th style="text-align: right;">CONTROL</th>
<th style="text-align: right;">ADM_RATE</th>
<th style="text-align: right;">SATVR25</th>
<th style="text-align: right;">SATVR75</th>
<th style="text-align: right;">SATMT25</th>
<th style="text-align: right;">SATMT75</th>
<th style="text-align: right;">SATWR25</th>
<th style="text-align: right;">SATWR75</th>
<th style="text-align: right;">SATVRMID</th>
<th style="text-align: right;">SATMTMID</th>
<th style="text-align: right;">SATWRMID</th>
<th style="text-align: right;">ACTCM25</th>
<th style="text-align: right;">ACTCM75</th>
<th style="text-align: right;">ACTEN25</th>
<th style="text-align: right;">ACTEN75</th>
<th style="text-align: right;">ACTMT25</th>
<th style="text-align: right;">ACTMT75</th>
<th style="text-align: right;">ACTWR25</th>
<th style="text-align: right;">ACTWR75</th>
<th style="text-align: right;">ACTCMMID</th>
<th style="text-align: right;">ACTENMID</th>
<th style="text-align: right;">ACTMTMID</th>
<th style="text-align: right;">ACTWRMID</th>
<th style="text-align: right;">SAT_AVG</th>
<th style="text-align: right;">UGDS</th>
<th style="text-align: left;">UG</th>
<th style="text-align: right;">UGDS_WHITE</th>
<th style="text-align: right;">UGDS_BLACK</th>
<th style="text-align: right;">UGDS_HISP</th>
<th style="text-align: right;">UGDS_ASIAN</th>
<th style="text-align: right;">UGDS_AIAN</th>
<th style="text-align: right;">UGDS_NHPI</th>
<th style="text-align: right;">UGDS_2MOR</th>
<th style="text-align: right;">UGDS_NRA</th>
<th style="text-align: right;">UGDS_UNKN</th>
<th style="text-align: right;">NPT4_PUB</th>
<th style="text-align: right;">NPT4_PRIV</th>
<th style="text-align: right;">COSTT4_A</th>
<th style="text-align: right;">COSTT4_P</th>
<th style="text-align: right;">AVGFACSAL</th>
<th style="text-align: right;">PCTPELL</th>
<th style="text-align: right;">C150_4</th>
<th style="text-align: right;">AGE_ENTRY</th>
<th style="text-align: right;">FEMALE</th>
<th style="text-align: right;">MARRIED</th>
<th style="text-align: right;">FIRST_GEN</th>
<th style="text-align: right;">FAMINC</th>
<th style="text-align: right;">MD_FAMINC</th>
<th style="text-align: right;">MN_EARN_WNE_P10</th>
<th style="text-align: right;">MD_EARN_WNE_P10</th>
<th style="text-align: right;">ENDOWBEGIN</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Massachusetts Institute of Technology</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">166683</td>
<td style="text-align: right;">217800</td>
<td style="text-align: right;">2178</td>
<td style="text-align: left;">Cambridge</td>
<td style="text-align: left;">MA</td>
<td style="text-align: left;">02139-4307</td>
<td style="text-align: left;">New England Commission on Higher Education</td>
<td style="text-align: right;">42.35924</td>
<td style="text-align: right;">-71.09323</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.0726</td>
<td style="text-align: right;">730</td>
<td style="text-align: right;">780</td>
<td style="text-align: right;">780</td>
<td style="text-align: right;">800</td>
<td style="text-align: right;">690</td>
<td style="text-align: right;">780</td>
<td style="text-align: right;">755</td>
<td style="text-align: right;">790</td>
<td style="text-align: right;">735</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">1550</td>
<td style="text-align: right;">4360</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.2562</td>
<td style="text-align: right;">0.0670</td>
<td style="text-align: right;">0.1557</td>
<td style="text-align: right;">0.3236</td>
<td style="text-align: right;">0.0018</td>
<td style="text-align: right;">0.0007</td>
<td style="text-align: right;">0.0764</td>
<td style="text-align: right;">0.1028</td>
<td style="text-align: right;">0.0158</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">16407</td>
<td style="text-align: right;">73160</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">19640</td>
<td style="text-align: right;">0.1896</td>
<td style="text-align: right;">0.9558</td>
<td style="text-align: right;">19.34846</td>
<td style="text-align: right;">0.3718887</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.2585139</td>
<td style="text-align: right;">86738.82</td>
<td style="text-align: right;">53870</td>
<td style="text-align: right;">153600</td>
<td style="text-align: right;">111222</td>
<td style="text-align: right;">17443750000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stanford University</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">243744</td>
<td style="text-align: right;">130500</td>
<td style="text-align: right;">1305</td>
<td style="text-align: left;">Stanford</td>
<td style="text-align: left;">CA</td>
<td style="text-align: left;">94305</td>
<td style="text-align: left;">Western Association of Schools and Colleges Senior Colleges and University Commission</td>
<td style="text-align: right;">37.42943</td>
<td style="text-align: right;">-122.16736</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.0519</td>
<td style="text-align: right;">700</td>
<td style="text-align: right;">770</td>
<td style="text-align: right;">720</td>
<td style="text-align: right;">800</td>
<td style="text-align: right;">690</td>
<td style="text-align: right;">780</td>
<td style="text-align: right;">735</td>
<td style="text-align: right;">760</td>
<td style="text-align: right;">735</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1491</td>
<td style="text-align: right;">6366</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.2900</td>
<td style="text-align: right;">0.0743</td>
<td style="text-align: right;">0.1700</td>
<td style="text-align: right;">0.2480</td>
<td style="text-align: right;">0.0097</td>
<td style="text-align: right;">0.0035</td>
<td style="text-align: right;">0.0957</td>
<td style="text-align: right;">0.1067</td>
<td style="text-align: right;">0.0022</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">12894</td>
<td style="text-align: right;">74570</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">20971</td>
<td style="text-align: right;">0.1762</td>
<td style="text-align: right;">0.9523</td>
<td style="text-align: right;">19.70933</td>
<td style="text-align: right;">0.4940191</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.3033854</td>
<td style="text-align: right;">80447.91</td>
<td style="text-align: right;">44842</td>
<td style="text-align: right;">141300</td>
<td style="text-align: right;">97798</td>
<td style="text-align: right;">27699834000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Harvard University</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">166027</td>
<td style="text-align: right;">215500</td>
<td style="text-align: right;">2155</td>
<td style="text-align: left;">Cambridge</td>
<td style="text-align: left;">MA</td>
<td style="text-align: left;">2138</td>
<td style="text-align: left;">New England Commission on Higher Education</td>
<td style="text-align: right;">42.37447</td>
<td style="text-align: right;">-71.11831</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.0501</td>
<td style="text-align: right;">720</td>
<td style="text-align: right;">780</td>
<td style="text-align: right;">740</td>
<td style="text-align: right;">800</td>
<td style="text-align: right;">710</td>
<td style="text-align: right;">790</td>
<td style="text-align: right;">750</td>
<td style="text-align: right;">770</td>
<td style="text-align: right;">750</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">1520</td>
<td style="text-align: right;">6099</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.3596</td>
<td style="text-align: right;">0.1058</td>
<td style="text-align: right;">0.1230</td>
<td style="text-align: right;">0.2066</td>
<td style="text-align: right;">0.0025</td>
<td style="text-align: right;">0.0016</td>
<td style="text-align: right;">0.0689</td>
<td style="text-align: right;">0.1123</td>
<td style="text-align: right;">0.0198</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">13872</td>
<td style="text-align: right;">75914</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">21143</td>
<td style="text-align: right;">0.1133</td>
<td style="text-align: right;">0.9763</td>
<td style="text-align: right;">22.46359</td>
<td style="text-align: right;">0.5015385</td>
<td style="text-align: right;">0.0635897</td>
<td style="text-align: right;">0.2570806</td>
<td style="text-align: right;">62458.19</td>
<td style="text-align: right;">33066</td>
<td style="text-align: right;">139100</td>
<td style="text-align: right;">84918</td>
<td style="text-align: right;">40929700000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yale University</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">130794</td>
<td style="text-align: right;">142600</td>
<td style="text-align: right;">1426</td>
<td style="text-align: left;">New Haven</td>
<td style="text-align: left;">CT</td>
<td style="text-align: left;">6520</td>
<td style="text-align: left;">New England Commission on Higher Education</td>
<td style="text-align: right;">41.31116</td>
<td style="text-align: right;">-72.92669</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.0653</td>
<td style="text-align: right;">720</td>
<td style="text-align: right;">780</td>
<td style="text-align: right;">740</td>
<td style="text-align: right;">800</td>
<td style="text-align: right;">710</td>
<td style="text-align: right;">790</td>
<td style="text-align: right;">750</td>
<td style="text-align: right;">770</td>
<td style="text-align: right;">750</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1520</td>
<td style="text-align: right;">4701</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.3493</td>
<td style="text-align: right;">0.0910</td>
<td style="text-align: right;">0.1504</td>
<td style="text-align: right;">0.2389</td>
<td style="text-align: right;">0.0028</td>
<td style="text-align: right;">0.0011</td>
<td style="text-align: right;">0.0623</td>
<td style="text-align: right;">0.1004</td>
<td style="text-align: right;">0.0038</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">15296</td>
<td style="text-align: right;">76645</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">19490</td>
<td style="text-align: right;">0.1840</td>
<td style="text-align: right;">0.9639</td>
<td style="text-align: right;">19.53215</td>
<td style="text-align: right;">0.5006840</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.2500000</td>
<td style="text-align: right;">80258.13</td>
<td style="text-align: right;">44004</td>
<td style="text-align: right;">124400</td>
<td style="text-align: right;">88655</td>
<td style="text-align: right;">30314816000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Princeton University</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">186131</td>
<td style="text-align: right;">262700</td>
<td style="text-align: right;">2627</td>
<td style="text-align: left;">Princeton</td>
<td style="text-align: left;">NJ</td>
<td style="text-align: left;">08544-0070</td>
<td style="text-align: left;">Middle States Commission on Higher Education</td>
<td style="text-align: right;">40.34873</td>
<td style="text-align: right;">-74.65936</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.0563</td>
<td style="text-align: right;">710</td>
<td style="text-align: right;">770</td>
<td style="text-align: right;">740</td>
<td style="text-align: right;">800</td>
<td style="text-align: right;">710</td>
<td style="text-align: right;">790</td>
<td style="text-align: right;">740</td>
<td style="text-align: right;">770</td>
<td style="text-align: right;">750</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">1506</td>
<td style="text-align: right;">4688</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0.3631</td>
<td style="text-align: right;">0.0892</td>
<td style="text-align: right;">0.1064</td>
<td style="text-align: right;">0.2515</td>
<td style="text-align: right;">0.0019</td>
<td style="text-align: right;">0.0011</td>
<td style="text-align: right;">0.0591</td>
<td style="text-align: right;">0.1165</td>
<td style="text-align: right;">0.0113</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">9836</td>
<td style="text-align: right;">74150</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">20835</td>
<td style="text-align: right;">0.2136</td>
<td style="text-align: right;">0.9802</td>
<td style="text-align: right;">19.25682</td>
<td style="text-align: right;">0.5136437</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.2773973</td>
<td style="text-align: right;">63667.64</td>
<td style="text-align: right;">37036</td>
<td style="text-align: right;">116300</td>
<td style="text-align: right;">95689</td>
<td style="text-align: right;">25623628250</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol start="4" type="1">
<li>Then, we selected the variables that we thought could have an impact on college ranking as a starting point for our analysis. These are listed in our data summary.</li>
</ol>
<div class="cell">

</div>
<ol start="5" type="1">
<li>Some of the categorical variables in the US Department of Education dataset (<code>REGION</code>, <code>CONTROL</code>, and <code>CCBASIC</code>) used numbers to represent the different levels, so we looked at the data dictionary and replaced each number with the words that it represents.</li>
</ol>
<div class="cell">

</div>
<ol start="6" type="1">
<li>All of the numerical variables are on different scales—for example, SAT scores can range from 400 to 1600, while admittance rate can only range from 0 to 1—and so we standardized them for easier analysis and comparison. We used the <code>scale()</code> functions (found at https://www.statology.org/standardize-data-in-r/) to make the mean value of each numeric variable 0, and the standard deviation 1. The first 5 rows of our standardized dataset are printed below.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 7%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">college</th>
<th style="text-align: right;">rank</th>
<th style="text-align: left;">REGION</th>
<th style="text-align: left;">CONTROL</th>
<th style="text-align: left;">CCBASIC</th>
<th style="text-align: left;">ACCREDAGENCY</th>
<th style="text-align: right;">ADM_RATE</th>
<th style="text-align: right;">UGDS</th>
<th style="text-align: right;">UGDS_WHITE</th>
<th style="text-align: right;">UGDS_BLACK</th>
<th style="text-align: right;">UGDS_HISP</th>
<th style="text-align: right;">UGDS_ASIAN</th>
<th style="text-align: right;">UGDS_AIAN</th>
<th style="text-align: right;">UGDS_NHPI</th>
<th style="text-align: right;">UGDS_2MOR</th>
<th style="text-align: right;">UGDS_NRA</th>
<th style="text-align: right;">UGDS_UNKN</th>
<th style="text-align: right;">NPT4_PUB</th>
<th style="text-align: right;">NPT4_PRIV</th>
<th style="text-align: right;">COSTT4_A</th>
<th style="text-align: right;">COSTT4_P</th>
<th style="text-align: right;">AVGFACSAL</th>
<th style="text-align: right;">PCTPELL</th>
<th style="text-align: right;">C150_4</th>
<th style="text-align: right;">AGE_ENTRY</th>
<th style="text-align: right;">FEMALE</th>
<th style="text-align: right;">MARRIED</th>
<th style="text-align: right;">FIRST_GEN</th>
<th style="text-align: right;">FAMINC</th>
<th style="text-align: right;">MD_FAMINC</th>
<th style="text-align: right;">ENDOWBEGIN</th>
<th style="text-align: right;">SAT_AVG</th>
<th style="text-align: right;">ACTCMMID</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Massachusetts Institute of Technology</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">New England</td>
<td style="text-align: left;">Private, Non-profit</td>
<td style="text-align: left;">Doctoral Universities: Very High Research Activity</td>
<td style="text-align: left;">New England Commission on Higher Education</td>
<td style="text-align: right;">-2.248372</td>
<td style="text-align: right;">-0.4488165</td>
<td style="text-align: right;">-1.732837</td>
<td style="text-align: right;">-0.1214557</td>
<td style="text-align: right;">0.2428424</td>
<td style="text-align: right;">3.090479</td>
<td style="text-align: right;">-0.1022072</td>
<td style="text-align: right;">-0.3336011</td>
<td style="text-align: right;">1.2864474</td>
<td style="text-align: right;">0.9088314</td>
<td style="text-align: right;">-0.3792490</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-1.440486</td>
<td style="text-align: right;">1.347387</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.348112</td>
<td style="text-align: right;">-0.6132292</td>
<td style="text-align: right;">1.664275</td>
<td style="text-align: right;">-0.9403691</td>
<td style="text-align: right;">-1.7820795</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.0032383</td>
<td style="text-align: right;">0.2016238</td>
<td style="text-align: right;">-0.3635658</td>
<td style="text-align: right;">4.823077</td>
<td style="text-align: right;">2.435243</td>
<td style="text-align: right;">2.157264</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stanford University</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Far West</td>
<td style="text-align: left;">Private, Non-profit</td>
<td style="text-align: left;">Doctoral Universities: Very High Research Activity</td>
<td style="text-align: left;">Western Association of Schools and Colleges Senior Colleges and University Commission</td>
<td style="text-align: right;">-2.335695</td>
<td style="text-align: right;">-0.2691747</td>
<td style="text-align: right;">-1.552828</td>
<td style="text-align: right;">-0.0293488</td>
<td style="text-align: right;">0.3723680</td>
<td style="text-align: right;">2.137251</td>
<td style="text-align: right;">0.1234229</td>
<td style="text-align: right;">0.6073252</td>
<td style="text-align: right;">2.0710638</td>
<td style="text-align: right;">0.9834995</td>
<td style="text-align: right;">-0.8292621</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-1.900262</td>
<td style="text-align: right;">1.416553</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.815132</td>
<td style="text-align: right;">-0.7336406</td>
<td style="text-align: right;">1.639406</td>
<td style="text-align: right;">-0.7893840</td>
<td style="text-align: right;">-0.6603776</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.4512025</td>
<td style="text-align: right;">-0.0389967</td>
<td style="text-align: right;">-0.7457627</td>
<td style="text-align: right;">7.852658</td>
<td style="text-align: right;">1.959465</td>
<td style="text-align: right;">1.625002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Harvard University</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">New England</td>
<td style="text-align: left;">Private, Non-profit</td>
<td style="text-align: left;">Doctoral Universities: Very High Research Activity</td>
<td style="text-align: left;">New England Commission on Higher Education</td>
<td style="text-align: right;">-2.343288</td>
<td style="text-align: right;">-0.2930851</td>
<td style="text-align: right;">-1.182157</td>
<td style="text-align: right;">0.3680987</td>
<td style="text-align: right;">-0.0533455</td>
<td style="text-align: right;">1.615244</td>
<td style="text-align: right;">-0.0822146</td>
<td style="text-align: right;">-0.0311605</td>
<td style="text-align: right;">0.9815446</td>
<td style="text-align: right;">1.0907153</td>
<td style="text-align: right;">-0.2468922</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-1.772263</td>
<td style="text-align: right;">1.482482</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.875483</td>
<td style="text-align: right;">-1.2988551</td>
<td style="text-align: right;">1.809938</td>
<td style="text-align: right;">0.3629841</td>
<td style="text-align: right;">-0.5913166</td>
<td style="text-align: right;">-0.1349421</td>
<td style="text-align: right;">-0.0177544</td>
<td style="text-align: right;">-0.7270840</td>
<td style="text-align: right;">-1.2442952</td>
<td style="text-align: right;">11.760676</td>
<td style="text-align: right;">2.193322</td>
<td style="text-align: right;">1.891133</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yale University</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">New England</td>
<td style="text-align: left;">Private, Non-profit</td>
<td style="text-align: left;">Doctoral Universities: Very High Research Activity</td>
<td style="text-align: left;">New England Commission on Higher Education</td>
<td style="text-align: right;">-2.279167</td>
<td style="text-align: right;">-0.4182792</td>
<td style="text-align: right;">-1.237012</td>
<td style="text-align: right;">0.1813614</td>
<td style="text-align: right;">0.1948364</td>
<td style="text-align: right;">2.022510</td>
<td style="text-align: right;">-0.0736464</td>
<td style="text-align: right;">-0.1991831</td>
<td style="text-align: right;">0.7132302</td>
<td style="text-align: right;">0.8628818</td>
<td style="text-align: right;">-0.7763194</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-1.585892</td>
<td style="text-align: right;">1.518341</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.295480</td>
<td style="text-align: right;">-0.6635504</td>
<td style="text-align: right;">1.721830</td>
<td style="text-align: right;">-0.8635162</td>
<td style="text-align: right;">-0.5991644</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.0894640</td>
<td style="text-align: right;">-0.0462554</td>
<td style="text-align: right;">-0.7812391</td>
<td style="text-align: right;">8.625107</td>
<td style="text-align: right;">2.193322</td>
<td style="text-align: right;">1.891133</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Princeton University</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Mid East</td>
<td style="text-align: left;">Private, Non-profit</td>
<td style="text-align: left;">Doctoral Universities: Very High Research Activity</td>
<td style="text-align: left;">Middle States Commission on Higher Education</td>
<td style="text-align: right;">-2.317134</td>
<td style="text-align: right;">-0.4194434</td>
<td style="text-align: right;">-1.163517</td>
<td style="text-align: right;">0.1586502</td>
<td style="text-align: right;">-0.2037038</td>
<td style="text-align: right;">2.181382</td>
<td style="text-align: right;">-0.0993511</td>
<td style="text-align: right;">-0.1991831</td>
<td style="text-align: right;">0.5831383</td>
<td style="text-align: right;">1.1711271</td>
<td style="text-align: right;">-0.5281504</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-2.300489</td>
<td style="text-align: right;">1.395951</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">3.767412</td>
<td style="text-align: right;">-0.3975671</td>
<td style="text-align: right;">1.837650</td>
<td style="text-align: right;">-0.9787111</td>
<td style="text-align: right;">-0.4801369</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.1880047</td>
<td style="text-align: right;">-0.6808240</td>
<td style="text-align: right;">-1.0762267</td>
<td style="text-align: right;">7.239361</td>
<td style="text-align: right;">2.080425</td>
<td style="text-align: right;">1.891133</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="preliminary-exploration-and-visualization" class="level3">
<h3 class="anchored" data-anchor-id="preliminary-exploration-and-visualization">Preliminary Exploration and Visualization</h3>
<section id="means-of-different-variables-by-rank-group" class="level4">
<h4 class="anchored" data-anchor-id="means-of-different-variables-by-rank-group">Means of Different Variables by Rank Group</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Interval</th>
<th style="text-align: right;">Mean Admission Rate</th>
<th style="text-align: right;">Mean SAT Average</th>
<th style="text-align: right;">Mean ACT Median</th>
<th style="text-align: right;">Mean % White Students</th>
<th style="text-align: right;">Mean % Asian Students</th>
<th style="text-align: right;">Mean Cost of Attendance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1 to 100</td>
<td style="text-align: right;">0.2767340</td>
<td style="text-align: right;">1422.703</td>
<td style="text-align: right;">32.05495</td>
<td style="text-align: right;">0.4865770</td>
<td style="text-align: right;">0.1500930</td>
<td style="text-align: right;">60691.49</td>
</tr>
<tr class="even">
<td style="text-align: left;">101 to 200</td>
<td style="text-align: right;">0.6181010</td>
<td style="text-align: right;">1266.932</td>
<td style="text-align: right;">27.45455</td>
<td style="text-align: right;">0.6271786</td>
<td style="text-align: right;">0.0698429</td>
<td style="text-align: right;">46371.74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">201 to 300</td>
<td style="text-align: right;">0.6818970</td>
<td style="text-align: right;">1215.864</td>
<td style="text-align: right;">26.02469</td>
<td style="text-align: right;">0.6142470</td>
<td style="text-align: right;">0.0729400</td>
<td style="text-align: right;">43882.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">301 to 400</td>
<td style="text-align: right;">0.7157737</td>
<td style="text-align: right;">1160.091</td>
<td style="text-align: right;">24.14474</td>
<td style="text-align: right;">0.5629051</td>
<td style="text-align: right;">0.0548111</td>
<td style="text-align: right;">40799.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">401 to 500</td>
<td style="text-align: right;">0.7430135</td>
<td style="text-align: right;">1145.662</td>
<td style="text-align: right;">23.86076</td>
<td style="text-align: right;">0.6184102</td>
<td style="text-align: right;">0.0436867</td>
<td style="text-align: right;">36583.50</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>After grouping the schools into five groups of 100 by their rank, we see that different metrics vary considerably across the group. As the rank level gets higher, the mean admission rate increases, the mean SAT Average decreases, the mean ACT Median decreases, and the cost of attendance decreases. As far as demographic statistics, 1-100 ranked schools have considerably fewer White students and considerably more Asian students than schools ranked above 100.</p>
</section>
<section id="means-of-rank-by-categorical-variables" class="level4">
<h4 class="anchored" data-anchor-id="means-of-rank-by-categorical-variables">Means of Rank by Categorical Variables</h4>
<p>Below, we group the schools by the different categorical variables in our analysis and then take the mean rank for each of those groups.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">Control</th>
<th style="text-align: right;">Mean Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Private, Non-profit</td>
<td style="text-align: right;">236.568</td>
</tr>
<tr class="even">
<td style="text-align: left;">Public</td>
<td style="text-align: right;">269.670</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Private, For-profit</td>
<td style="text-align: right;">360.750</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We observe that private non-profit colleges have a higher mean rank than public colleges or private for-profit colleges.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">Region</th>
<th style="text-align: right;">Mean Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NA</td>
<td style="text-align: right;">81.5000</td>
</tr>
<tr class="even">
<td style="text-align: left;">New England</td>
<td style="text-align: right;">162.9070</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Far West</td>
<td style="text-align: right;">222.6102</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mid East</td>
<td style="text-align: right;">229.7416</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Great Lakes</td>
<td style="text-align: right;">260.5362</td>
</tr>
<tr class="even">
<td style="text-align: left;">Southeast</td>
<td style="text-align: right;">273.7627</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rocky Mountains</td>
<td style="text-align: right;">273.8000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Southwest</td>
<td style="text-align: right;">285.5122</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Plains</td>
<td style="text-align: right;">293.2632</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As far as region, schools from New England have the highest mean rank, while schools from the Plains have the lowest mean rank.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 87%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Carnegie Classification (Basic)</th>
<th style="text-align: right;">Mean Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Special Focus Four-Year: Business &amp; Management Schools</td>
<td style="text-align: right;">55.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Doctoral Universities: Very High Research Activity</td>
<td style="text-align: right;">123.8629</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Special Focus Four-Year: Engineering Schools</td>
<td style="text-align: right;">148.5000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baccalaureate Colleges: Arts &amp; Sciences Focus</td>
<td style="text-align: right;">199.4045</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Special Focus Four-Year: Faith-Related Institutions</td>
<td style="text-align: right;">213.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baccalaureate/Associate’s Colleges: Mixed Baccalaureate/Associate’s</td>
<td style="text-align: right;">248.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Special Focus Four-Year: Other Health Professions Schools</td>
<td style="text-align: right;">268.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Doctoral Universities: High Research Activity</td>
<td style="text-align: right;">279.5663</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Master’s Colleges &amp; Universities: Small Programs</td>
<td style="text-align: right;">307.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baccalaureate Colleges: Diverse Fields</td>
<td style="text-align: right;">313.3500</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Special Focus Four-Year: Arts, Music &amp; Design Schools</td>
<td style="text-align: right;">329.5000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Doctoral/Professional Universities</td>
<td style="text-align: right;">331.5962</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Special Focus Four-Year: Other Special Focus Institutions</td>
<td style="text-align: right;">351.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Master’s Colleges &amp; Universities: Larger Programs</td>
<td style="text-align: right;">363.2727</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Master’s Colleges &amp; Universities: Medium Programs</td>
<td style="text-align: right;">365.2069</td>
</tr>
<tr class="even">
<td style="text-align: left;">Special Focus Four-Year: Other Technology-Related Schools</td>
<td style="text-align: right;">385.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NA</td>
<td style="text-align: right;">430.6667</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tribal Colleges</td>
<td style="text-align: right;">453.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Looking at the Carnegie Classification, Special Focus Four-Year: Business &amp; Management Schools have the highest mean rank, followed by Doctoral Universities: Very High Research Activity. Tribal Colleges have the lowest mean rank.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">State</th>
<th style="text-align: right;">Mean Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ME</td>
<td style="text-align: right;">107.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA</td>
<td style="text-align: right;">123.5238</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DE</td>
<td style="text-align: right;">143.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">CT</td>
<td style="text-align: right;">166.4286</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VT</td>
<td style="text-align: right;">167.5000</td>
</tr>
<tr class="even">
<td style="text-align: left;">CA</td>
<td style="text-align: right;">172.3333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DC</td>
<td style="text-align: right;">174.2000</td>
</tr>
<tr class="even">
<td style="text-align: left;">GA</td>
<td style="text-align: right;">191.6667</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OK</td>
<td style="text-align: right;">196.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">WY</td>
<td style="text-align: right;">200.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>When looking at states, Maine has the highest mean rank, followed by Massachusetts.</p>
</section>
<section id="numerical-variables-vs.-rank" class="level4">
<h4 class="anchored" data-anchor-id="numerical-variables-vs.-rank">Numerical Variables vs.&nbsp;Rank</h4>
<p>We have plotted rank versus several of the numerical variables. This gives us an idea of how different metrics affect college rank.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-5.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-6.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-7.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-8.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-9.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-10.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-11.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-12.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-13.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-14.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-15.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-16.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-17.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-18.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-19.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-20.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-21.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-22.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-23.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-13-24.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/arrange-in-grid-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From these graphs, there appears to be a very strong positive association between admission rate/ % of undergrads on Pell grants and college rank. There appears to be somewhat of a positive association between % of undergrads who are white/% of first generation students and college ranks. This means that as these metrics decrease, the rank of a school is expected to decrease</p>
<p>There appears to be a strong negative association between % of undergrads who are Asian/% of undergrads who are non-resident aliens/average faculty salary/graduation rate and college rank. There appears to be somewhat of a negative relationship between average net price for private universities/cost of attendance/average family income/median family income and college rank. This means that as these metrics increase, the rank of a school is expected to increase.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/arrange-in-grid-test-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>For all type of standardized test scores, there appear to be a strong negative relationship between score and rank, indicating that as the test scores increases, the rank of a school is expected to to increase.</p>
</section>
</section>
<section id="check-correlation-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="check-correlation-coefficients">Check Correlation Coefficients</h3>
<p>We checked the correlation coefficients between the variables so we don’t use variables that are too similar in our model. For the ones that have a absolute value of r greater than 0.8, we picked only one to put in the model. We removed the columns that has more than 100 NA and used the rest for calculating correlations.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>According to the correlation matrix, we need to remove variable pairs that have a high correlation (the absolute value &gt; 0.8). In order to do so, we filter the following correlation table to only display entries with value greater or equal to 0.8.</p>
<div class="cell">

</div>
<table class="table">
<thead>
<tr class="header">
<th>Variable Pairs with r &gt; 0.8</th>
<th>Correlation Coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C150_4, SAT_AVG</td>
<td>0.8389</td>
</tr>
<tr class="even">
<td>C150_4, ACTCMMID</td>
<td>0.8494</td>
</tr>
<tr class="odd">
<td>AGE_ENTRY, MARRIED</td>
<td>0.9059</td>
</tr>
<tr class="even">
<td>FAMINC, MD_FAMINC</td>
<td>0.9538</td>
</tr>
<tr class="odd">
<td>SAT_AVG, ACTCMMID</td>
<td>0.9756</td>
</tr>
</tbody>
</table>
<p>According to the filtered table, these variable pairs are (MD_FAMINC, FAMINC), (C150_4, SAT_AVG), (C150_4, ACTCMMID) and (ACTCMMID, SAT_AVG). Therefore, we will drop the variables C150_4, MD_FAMINC, ACTCMMID and preserve SAT_AVG and FAMINC to represent all other variables.</p>
</section>
<section id="build-model" class="level3">
<h3 class="anchored" data-anchor-id="build-model">Build model</h3>
<p>Because we want to predict college rank, a number from various variables, we decided that a linear regression model would be the best statistical method to answer our question. We began our modeling by removing the variables with a correlation coefficient above 0.8.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">Selected Variables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">college</td>
</tr>
<tr class="even">
<td style="text-align: left;">rank</td>
</tr>
<tr class="odd">
<td style="text-align: left;">REGION</td>
</tr>
<tr class="even">
<td style="text-align: left;">CONTROL</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CCBASIC</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACCREDAGENCY</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ADM_RATE</td>
</tr>
<tr class="even">
<td style="text-align: left;">UGDS</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS_WHITE</td>
</tr>
<tr class="even">
<td style="text-align: left;">UGDS_BLACK</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS_HISP</td>
</tr>
<tr class="even">
<td style="text-align: left;">UGDS_ASIAN</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS_AIAN</td>
</tr>
<tr class="even">
<td style="text-align: left;">UGDS_NHPI</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS_2MOR</td>
</tr>
<tr class="even">
<td style="text-align: left;">UGDS_NRA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS_UNKN</td>
</tr>
<tr class="even">
<td style="text-align: left;">COSTT4_A</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AVGFACSAL</td>
</tr>
<tr class="even">
<td style="text-align: left;">PCTPELL</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AGE_ENTRY</td>
</tr>
<tr class="even">
<td style="text-align: left;">FAMINC</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ENDOWBEGIN</td>
</tr>
<tr class="even">
<td style="text-align: left;">SAT_AVG</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FEMALE</td>
</tr>
<tr class="even">
<td style="text-align: left;">MARRIED</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FIRST_GEN</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Then we need to split dataset into two parts: a training and a test set. We will use 80% of the college data for training our model and the other 20% for testing our model.</p>
<div class="cell">

</div>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="categorical-variable-analysis" class="level3">
<h3 class="anchored" data-anchor-id="categorical-variable-analysis">Categorical Variable Analysis</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/rank-vs-region-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/rank-vs-region-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/rank-vs-accredation-agency-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/rank-vs-accredation-agency-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/rank-vs-control-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/rank-vs-control-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/rank-vs-CCBASIC-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/rank-vs-CCBASIC-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There appear to be the greatest differences between bars of proportions of rank groups in the Carnegie Classification group, suggesting that this has the strongest association with rank.</p>
</section>
<section id="iteration-1" class="level3">
<h3 class="anchored" data-anchor-id="iteration-1">Iteration #1</h3>
<p>We begin with creating the first model based on the numerical variables that we chose for the data and created an additive model that considered how the variables influenced the rank of the college.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">246.2027925</td>
<td style="text-align: right;">4.703871</td>
<td style="text-align: right;">52.3404663</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">ADM_RATE</td>
<td style="text-align: right;">35.6018194</td>
<td style="text-align: right;">7.629838</td>
<td style="text-align: right;">4.6661307</td>
<td style="text-align: right;">0.0000046</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS</td>
<td style="text-align: right;">-41.1973274</td>
<td style="text-align: right;">6.928463</td>
<td style="text-align: right;">-5.9460994</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">UGDS_WHITE</td>
<td style="text-align: right;">10732.7749048</td>
<td style="text-align: right;">10599.772816</td>
<td style="text-align: right;">1.0125476</td>
<td style="text-align: right;">0.3120710</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS_BLACK</td>
<td style="text-align: right;">4533.2629889</td>
<td style="text-align: right;">4474.426742</td>
<td style="text-align: right;">1.0131494</td>
<td style="text-align: right;">0.3117840</td>
</tr>
<tr class="even">
<td style="text-align: left;">UGDS_HISP</td>
<td style="text-align: right;">6313.6053442</td>
<td style="text-align: right;">6232.516748</td>
<td style="text-align: right;">1.0130106</td>
<td style="text-align: right;">0.3118502</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS_ASIAN</td>
<td style="text-align: right;">4541.8380285</td>
<td style="text-align: right;">4477.565288</td>
<td style="text-align: right;">1.0143544</td>
<td style="text-align: right;">0.3112098</td>
</tr>
<tr class="even">
<td style="text-align: left;">UGDS_AIAN</td>
<td style="text-align: right;">1926.4404448</td>
<td style="text-align: right;">1973.880100</td>
<td style="text-align: right;">0.9759663</td>
<td style="text-align: right;">0.3298471</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS_NHPI</td>
<td style="text-align: right;">163.9398183</td>
<td style="text-align: right;">167.303350</td>
<td style="text-align: right;">0.9798956</td>
<td style="text-align: right;">0.3279067</td>
</tr>
<tr class="even">
<td style="text-align: left;">UGDS_2MOR</td>
<td style="text-align: right;">1407.8496454</td>
<td style="text-align: right;">1388.644877</td>
<td style="text-align: right;">1.0138299</td>
<td style="text-align: right;">0.3114597</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS_NRA</td>
<td style="text-align: right;">2973.0798562</td>
<td style="text-align: right;">2948.226876</td>
<td style="text-align: right;">1.0084298</td>
<td style="text-align: right;">0.3140397</td>
</tr>
<tr class="even">
<td style="text-align: left;">UGDS_UNKN</td>
<td style="text-align: right;">1735.7967205</td>
<td style="text-align: right;">1705.950405</td>
<td style="text-align: right;">1.0174954</td>
<td style="text-align: right;">0.3097164</td>
</tr>
<tr class="odd">
<td style="text-align: left;">COSTT4_A</td>
<td style="text-align: right;">0.8428333</td>
<td style="text-align: right;">10.525477</td>
<td style="text-align: right;">0.0800755</td>
<td style="text-align: right;">0.9362292</td>
</tr>
<tr class="even">
<td style="text-align: left;">AVGFACSAL</td>
<td style="text-align: right;">-19.8005704</td>
<td style="text-align: right;">8.998855</td>
<td style="text-align: right;">-2.2003434</td>
<td style="text-align: right;">0.0285247</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PCTPELL</td>
<td style="text-align: right;">2.8162537</td>
<td style="text-align: right;">10.541378</td>
<td style="text-align: right;">0.2671618</td>
<td style="text-align: right;">0.7895234</td>
</tr>
<tr class="even">
<td style="text-align: left;">AGE_ENTRY</td>
<td style="text-align: right;">-12.0862558</td>
<td style="text-align: right;">7.334480</td>
<td style="text-align: right;">-1.6478682</td>
<td style="text-align: right;">0.1003994</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FAMINC</td>
<td style="text-align: right;">-22.9537106</td>
<td style="text-align: right;">11.800114</td>
<td style="text-align: right;">-1.9452109</td>
<td style="text-align: right;">0.0526593</td>
</tr>
<tr class="even">
<td style="text-align: left;">ENDOWBEGIN</td>
<td style="text-align: right;">1.3023057</td>
<td style="text-align: right;">6.035923</td>
<td style="text-align: right;">0.2157592</td>
<td style="text-align: right;">0.8293183</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SAT_AVG</td>
<td style="text-align: right;">-67.4876184</td>
<td style="text-align: right;">12.876049</td>
<td style="text-align: right;">-5.2413296</td>
<td style="text-align: right;">0.0000003</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>At a first glance, variables with negative slopes mean that they have a negative correlation to ranking. For example, the higher the <code>SAT_AVG</code>, the lower the college is ranked on a numerical scale. So the college is technically ranked higher.</p>
<p>Variables UGDS_NRA, UGDS_UNKN, COSTT4_A, PCTPELL, AGE_ENTRY, UGDS_WHITE, UGDS_BLACK, UGDS_HISP, UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR and ENDOWBEGIN are have a relative high p-value around or above 0.3, which is much greater than 0.05. Therefore, we will drop these variables for the next model iteration.</p>
<p>Then, we can evaluate our first primitive model by R-squared:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">adj.r.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7199576</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As we can see the model’s adjusted R-squared is around 72.0%.</p>
</section>
<section id="iteration-2" class="level3">
<h3 class="anchored" data-anchor-id="iteration-2">Iteration #2</h3>
<p>First, we will avoid using the variables with high p-values as mentioned above to train a new model.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">249.37044</td>
<td style="text-align: right;">4.506181</td>
<td style="text-align: right;">55.339648</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">ADM_RATE</td>
<td style="text-align: right;">27.21518</td>
<td style="text-align: right;">6.659181</td>
<td style="text-align: right;">4.086866</td>
<td style="text-align: right;">0.0000551</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS</td>
<td style="text-align: right;">-33.32915</td>
<td style="text-align: right;">4.895297</td>
<td style="text-align: right;">-6.808403</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AVGFACSAL</td>
<td style="text-align: right;">-10.80730</td>
<td style="text-align: right;">7.134635</td>
<td style="text-align: right;">-1.514766</td>
<td style="text-align: right;">0.1308007</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SAT_AVG</td>
<td style="text-align: right;">-86.86569</td>
<td style="text-align: right;">7.796687</td>
<td style="text-align: right;">-11.141359</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Then we can evaluation our second model by Rsqure:</p>
<pre><code>glance(fit2) |&gt;
  select(adj.r.squared) |&gt; knitr::kable()</code></pre>
<p>Since the R-squared value is 0.703 which is even smaller than 0.7200 of our first model, we need to implement forward selection by adding variables back to our model.</p>
</section>
<section id="iteration-3" class="level3">
<h3 class="anchored" data-anchor-id="iteration-3">Iteration #3</h3>
<p>From our first and second iteration, AGE_ENTRY, among the variables removed, has the smallest p-value of 0.1. Therefore we are going to add AGE_ENTRY back to our model for the iteration.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">249.7168722</td>
<td style="text-align: right;">4.523580</td>
<td style="text-align: right;">55.2033783</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">ADM_RATE</td>
<td style="text-align: right;">26.2874687</td>
<td style="text-align: right;">6.797196</td>
<td style="text-align: right;">3.8673990</td>
<td style="text-align: right;">0.0001330</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS</td>
<td style="text-align: right;">-33.2547774</td>
<td style="text-align: right;">4.923043</td>
<td style="text-align: right;">-6.7549237</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AVGFACSAL</td>
<td style="text-align: right;">-11.4385472</td>
<td style="text-align: right;">7.165074</td>
<td style="text-align: right;">-1.5964311</td>
<td style="text-align: right;">0.1113674</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SAT_AVG</td>
<td style="text-align: right;">-86.6323357</td>
<td style="text-align: right;">8.515896</td>
<td style="text-align: right;">-10.1730147</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AGE_ENTRY</td>
<td style="text-align: right;">0.4599436</td>
<td style="text-align: right;">5.802186</td>
<td style="text-align: right;">0.0792707</td>
<td style="text-align: right;">0.9368662</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">adj.r.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.701619</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The model accuracy is still not as good as the first model which means we need further forward selection by adding more variables back.</p>
</section>
<section id="iteration-4" class="level3">
<h3 class="anchored" data-anchor-id="iteration-4">Iteration #4</h3>
<p>From our first and second iteration, UGDS_UNKN, among the variables removed, has the smallest p-value of 0.310. Therefore we are going to add UGDS_UNKN back to our model for the iteration.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">249.7153091</td>
<td style="text-align: right;">4.521131</td>
<td style="text-align: right;">55.232924</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">ADM_RATE</td>
<td style="text-align: right;">27.2202655</td>
<td style="text-align: right;">6.840754</td>
<td style="text-align: right;">3.979132</td>
<td style="text-align: right;">0.0000854</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS</td>
<td style="text-align: right;">-32.7123939</td>
<td style="text-align: right;">4.942456</td>
<td style="text-align: right;">-6.618652</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AVGFACSAL</td>
<td style="text-align: right;">-11.1617082</td>
<td style="text-align: right;">7.165156</td>
<td style="text-align: right;">-1.557776</td>
<td style="text-align: right;">0.1202656</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SAT_AVG</td>
<td style="text-align: right;">-86.3294688</td>
<td style="text-align: right;">8.515275</td>
<td style="text-align: right;">-10.138190</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">AGE_ENTRY</td>
<td style="text-align: right;">-0.8911943</td>
<td style="text-align: right;">5.914406</td>
<td style="text-align: right;">-0.150682</td>
<td style="text-align: right;">0.8803207</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UGDS_UNKN</td>
<td style="text-align: right;">5.4065047</td>
<td style="text-align: right;">4.651444</td>
<td style="text-align: right;">1.162328</td>
<td style="text-align: right;">0.2459603</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">adj.r.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7019419</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>While this model proved better than the previous one, it is still not as good as our initial model.</p>
</section>
<section id="model-results" class="level3">
<h3 class="anchored" data-anchor-id="model-results">Model results</h3>
<p>Because our initial model had the highest r-squared value of 0.7354, we can consider that to be our best model for predicting college ranking. However, in an effort to determine which variables have the most significant impact on college ranking, we can look at those with the lowest p-values: <code>ADM_RATE</code>, <code>UGDS</code>, <code>AVGFACSAL</code>, and <code>SAT_AVG</code>. Then, we can further single out the most significant variable with R-squared values.</p>
</section>
<section id="r-squared-values" class="level3">
<h3 class="anchored" data-anchor-id="r-squared-values">R-Squared Values</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/adm-rate-vs-rank-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.4153932</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The relationship between admission rate and college ranking gives us an R-squared value of 0.415 which is not that good and shows that admission rate might not be as significant as we originally thought.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/ugds-vs-rank-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.0479294</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As evident from the graph and the given R-squared value of 0.048, undergraduate enrollment has almost no impact on a college’s ranking.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/avgfacsal-vs-rank-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.4768954</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>While still relatively low, the R-squared value of 0.477 for the relationship between average faculty salary and ranking is higher than that of admission rate vs rank. This signifies that average faculty salary is a slightly more significant variable in predicting college ranking than admission rate.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="report_files/figure-html/sat-avg-vs-rank-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on the plot above, a college’s average SAT score has an almost semi-linear impact on it’s ranking. Typically, as average SAT score increases, a college’s ranking improves. Furthermore, we can see how well correlated these two variables are by creating a linear model.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.6410464</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>While an R-squared value of 0.641 is not the best, it is still the highest out of these variables which means that we can conclude that average SAT score has the greatest impact on a college ranking.</p>
</section>
<section id="final-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="final-conclusion">Final Conclusion</h3>
</section>
</section>
<section id="works-cited" class="level2">
<h2 class="anchored" data-anchor-id="works-cited">Works Cited</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>